### ISSUE TITLE
Doom2.wad - HUD flickers on Libdragon unstable.

### ISSUE THREAD

**Issue by nopjne** [thekovic/LibdragonDOOM#8]
The top half of the HUD keeps flickering on top of tree libdragon unstable.

**Comment by thekovic** [comment]
Are we talking ares or real hardware here?

**Comment by thekovic** [comment]
Okay, I can reproduce this now on ares. The HUD is only flickering if the pause menu is open, not during gameplay.

**Comment by nopjne** [comment]
Ive had it happen on real hw during gameplay.

**Comment by thekovic** [comment]
Hmm, okay. I'm away from N64 so I can't test right now on real hw. Can you try if the commit made any difference and reopen if not?

**Comment by nopjne** [comment]
confirming fix on real HW.

**Comment by thekovic** [comment]
Close for real by 3d04b73d000d24823fbd9e625777e2581b42af07
